<?php

namespace ContainerMxnTj8H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DohiXN2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dohiXN2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dohiXN2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'apiService' => ['privates', 'App\\Services\\ApiService', 'getApiServiceService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo_competence' => ['privates', 'App\\Repository\\CompetenceRepository', 'getCompetenceRepositoryService', true],
            'repo_cri_add' => ['privates', 'App\\Repository\\CritereAdmissionRepository', 'getCritereAdmissionRepositoryService', true],
            'repo_cri_eva' => ['privates', 'App\\Repository\\CritereEvaluationRepository', 'getCritereEvaluationRepositoryService', true],
            'repo_ref' => ['privates', 'App\\Repository\\ReferentielRepository', 'getReferentielRepositoryService', true],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
        ], [
            'apiService' => 'App\\Services\\ApiService',
            'em' => '?',
            'repo_competence' => 'App\\Repository\\CompetenceRepository',
            'repo_cri_add' => 'App\\Repository\\CritereAdmissionRepository',
            'repo_cri_eva' => 'App\\Repository\\CritereEvaluationRepository',
            'repo_ref' => 'App\\Repository\\ReferentielRepository',
            'serializer' => '?',
        ]);
    }
}
