<?php

namespace ContainerMxnTj8H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_3kTNFn2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.3kTNFn2' shared service.
     *
     * @return \App\Controller\Brie
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\BriefController::getPromoIdBriefsId()": the $repo_promo argument is type-hinted with the non-existent class or interface: "App\\Controller\\Brie". Did you forget to add a use statement?');
    }
}
