<?php

namespace ContainerMxnTj8H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I1tGUZHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i1tGUZH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i1tGUZH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'apiService' => ['privates', 'App\\Services\\ApiService', 'getApiServiceService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo_appre' => ['privates', 'App\\Repository\\ApprenantRepository', 'getApprenantRepositoryService', true],
            'repo_promo' => ['privates', 'App\\Repository\\PromoRepository', 'getPromoRepositoryService', true],
        ], [
            'apiService' => 'App\\Services\\ApiService',
            'em' => '?',
            'repo_appre' => 'App\\Repository\\ApprenantRepository',
            'repo_promo' => 'App\\Repository\\PromoRepository',
        ]);
    }
}
