<?php

namespace ContainerMxnTj8H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8UEXj8OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8UEXj8O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8UEXj8O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BriefController::getFormateurIdBriefsBroullon' => ['privates', '.service_locator.5Ll56vR', 'get_ServiceLocator_5Ll56vRService', true],
            'App\\Controller\\BriefController::getFormateurIdBriefsValider' => ['privates', '.service_locator.5Ll56vR', 'get_ServiceLocator_5Ll56vRService', true],
            'App\\Controller\\BriefController::getPromoIdBriefs' => ['privates', '.service_locator.zghYBvK', 'get_ServiceLocator_ZghYBvKService', true],
            'App\\Controller\\BriefController::getPromoIdBriefsId' => ['privates', '.service_locator.LSXm0.v', 'get_ServiceLocator_LSXm0_VService', true],
            'App\\Controller\\BriefController::getPromoIdGroupeIdBriefs' => ['privates', '.service_locator.zghYBvK', 'get_ServiceLocator_ZghYBvKService', true],
            'App\\Controller\\BriefController::postBriefs' => ['privates', '.service_locator.zs_LJzd', 'get_ServiceLocator_ZsLJzdService', true],
            'App\\Controller\\BriefController::postBriefsId' => ['privates', '.service_locator.5JO7VWi', 'get_ServiceLocator_5JO7VWiService', true],
            'App\\Controller\\GrCompetenceController::addGroupeComptence' => ['privates', '.service_locator.jfs2lN6', 'get_ServiceLocator_Jfs2lN6Service', true],
            'App\\Controller\\GrCompetenceController::updateGroupeComptence' => ['privates', '.service_locator.k2d8G12', 'get_ServiceLocator_K2d8G12Service', true],
            'App\\Controller\\PromoController::addPromo' => ['privates', '.service_locator.Gf0y2HJ', 'get_ServiceLocator_Gf0y2HJService', true],
            'App\\Controller\\PromoController::getPromoIdGroupId' => ['privates', '.service_locator.G84dhgw', 'get_ServiceLocator_G84dhgwService', true],
            'App\\Controller\\PromoController::getPromoIdGroupIdApprenants' => ['privates', '.service_locator.G84dhgw', 'get_ServiceLocator_G84dhgwService', true],
            'App\\Controller\\PromoController::updatePromoIdAppre' => ['privates', '.service_locator.i1tGUZH', 'get_ServiceLocator_I1tGUZHService', true],
            'App\\Controller\\PromoController::updatePromoIdForm' => ['privates', '.service_locator.xduXCoH', 'get_ServiceLocator_XduXCoHService', true],
            'App\\Controller\\PromoController::updatePromoIdGroupdId' => ['privates', '.service_locator.itct14d', 'get_ServiceLocator_Itct14dService', true],
            'App\\Controller\\ReferentielController::addReferentiel' => ['privates', '.service_locator.TtXkHWI', 'get_ServiceLocator_TtXkHWIService', true],
            'App\\Controller\\ReferentielController::updateReferentiel' => ['privates', '.service_locator.dohiXN2', 'get_ServiceLocator_DohiXN2Service', true],
            'App\\Controller\\UserController::addUser' => ['privates', '.service_locator.3txX.Ta', 'get_ServiceLocator_3txX_TaService', true],
            'App\\Controller\\UserController::updateUser' => ['privates', '.service_locator.6LPe79D', 'get_ServiceLocator_6LPe79DService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\BriefController:getFormateurIdBriefsBroullon' => ['privates', '.service_locator.5Ll56vR', 'get_ServiceLocator_5Ll56vRService', true],
            'App\\Controller\\BriefController:getFormateurIdBriefsValider' => ['privates', '.service_locator.5Ll56vR', 'get_ServiceLocator_5Ll56vRService', true],
            'App\\Controller\\BriefController:getPromoIdBriefs' => ['privates', '.service_locator.zghYBvK', 'get_ServiceLocator_ZghYBvKService', true],
            'App\\Controller\\BriefController:getPromoIdBriefsId' => ['privates', '.service_locator.LSXm0.v', 'get_ServiceLocator_LSXm0_VService', true],
            'App\\Controller\\BriefController:getPromoIdGroupeIdBriefs' => ['privates', '.service_locator.zghYBvK', 'get_ServiceLocator_ZghYBvKService', true],
            'App\\Controller\\BriefController:postBriefs' => ['privates', '.service_locator.zs_LJzd', 'get_ServiceLocator_ZsLJzdService', true],
            'App\\Controller\\BriefController:postBriefsId' => ['privates', '.service_locator.5JO7VWi', 'get_ServiceLocator_5JO7VWiService', true],
            'App\\Controller\\GrCompetenceController:addGroupeComptence' => ['privates', '.service_locator.jfs2lN6', 'get_ServiceLocator_Jfs2lN6Service', true],
            'App\\Controller\\GrCompetenceController:updateGroupeComptence' => ['privates', '.service_locator.k2d8G12', 'get_ServiceLocator_K2d8G12Service', true],
            'App\\Controller\\PromoController:addPromo' => ['privates', '.service_locator.Gf0y2HJ', 'get_ServiceLocator_Gf0y2HJService', true],
            'App\\Controller\\PromoController:getPromoIdGroupId' => ['privates', '.service_locator.G84dhgw', 'get_ServiceLocator_G84dhgwService', true],
            'App\\Controller\\PromoController:getPromoIdGroupIdApprenants' => ['privates', '.service_locator.G84dhgw', 'get_ServiceLocator_G84dhgwService', true],
            'App\\Controller\\PromoController:updatePromoIdAppre' => ['privates', '.service_locator.i1tGUZH', 'get_ServiceLocator_I1tGUZHService', true],
            'App\\Controller\\PromoController:updatePromoIdForm' => ['privates', '.service_locator.xduXCoH', 'get_ServiceLocator_XduXCoHService', true],
            'App\\Controller\\PromoController:updatePromoIdGroupdId' => ['privates', '.service_locator.itct14d', 'get_ServiceLocator_Itct14dService', true],
            'App\\Controller\\ReferentielController:addReferentiel' => ['privates', '.service_locator.TtXkHWI', 'get_ServiceLocator_TtXkHWIService', true],
            'App\\Controller\\ReferentielController:updateReferentiel' => ['privates', '.service_locator.dohiXN2', 'get_ServiceLocator_DohiXN2Service', true],
            'App\\Controller\\UserController:addUser' => ['privates', '.service_locator.3txX.Ta', 'get_ServiceLocator_3txX_TaService', true],
            'App\\Controller\\UserController:updateUser' => ['privates', '.service_locator.6LPe79D', 'get_ServiceLocator_6LPe79DService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\BriefController::getFormateurIdBriefsBroullon' => '?',
            'App\\Controller\\BriefController::getFormateurIdBriefsValider' => '?',
            'App\\Controller\\BriefController::getPromoIdBriefs' => '?',
            'App\\Controller\\BriefController::getPromoIdBriefsId' => '?',
            'App\\Controller\\BriefController::getPromoIdGroupeIdBriefs' => '?',
            'App\\Controller\\BriefController::postBriefs' => '?',
            'App\\Controller\\BriefController::postBriefsId' => '?',
            'App\\Controller\\GrCompetenceController::addGroupeComptence' => '?',
            'App\\Controller\\GrCompetenceController::updateGroupeComptence' => '?',
            'App\\Controller\\PromoController::addPromo' => '?',
            'App\\Controller\\PromoController::getPromoIdGroupId' => '?',
            'App\\Controller\\PromoController::getPromoIdGroupIdApprenants' => '?',
            'App\\Controller\\PromoController::updatePromoIdAppre' => '?',
            'App\\Controller\\PromoController::updatePromoIdForm' => '?',
            'App\\Controller\\PromoController::updatePromoIdGroupdId' => '?',
            'App\\Controller\\ReferentielController::addReferentiel' => '?',
            'App\\Controller\\ReferentielController::updateReferentiel' => '?',
            'App\\Controller\\UserController::addUser' => '?',
            'App\\Controller\\UserController::updateUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\BriefController:getFormateurIdBriefsBroullon' => '?',
            'App\\Controller\\BriefController:getFormateurIdBriefsValider' => '?',
            'App\\Controller\\BriefController:getPromoIdBriefs' => '?',
            'App\\Controller\\BriefController:getPromoIdBriefsId' => '?',
            'App\\Controller\\BriefController:getPromoIdGroupeIdBriefs' => '?',
            'App\\Controller\\BriefController:postBriefs' => '?',
            'App\\Controller\\BriefController:postBriefsId' => '?',
            'App\\Controller\\GrCompetenceController:addGroupeComptence' => '?',
            'App\\Controller\\GrCompetenceController:updateGroupeComptence' => '?',
            'App\\Controller\\PromoController:addPromo' => '?',
            'App\\Controller\\PromoController:getPromoIdGroupId' => '?',
            'App\\Controller\\PromoController:getPromoIdGroupIdApprenants' => '?',
            'App\\Controller\\PromoController:updatePromoIdAppre' => '?',
            'App\\Controller\\PromoController:updatePromoIdForm' => '?',
            'App\\Controller\\PromoController:updatePromoIdGroupdId' => '?',
            'App\\Controller\\ReferentielController:addReferentiel' => '?',
            'App\\Controller\\ReferentielController:updateReferentiel' => '?',
            'App\\Controller\\UserController:addUser' => '?',
            'App\\Controller\\UserController:updateUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
