<?php

namespace ContainerMxnTj8H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3txX_TaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3txX.Ta' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3txX.Ta'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'sr' => ['services', 'serializer', 'getSerializerService', false],
            'us_serice' => ['privates', 'App\\Services\\UserService', 'getUserServiceService', true],
        ], [
            'entityManager' => '?',
            'sr' => '?',
            'us_serice' => 'App\\Services\\UserService',
        ]);
    }
}
