<?php

namespace ContainerMxnTj8H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_FixturesLoadCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'doctrine.fixtures_load_command' shared service.
     *
     * @return \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Command/DoctrineCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Command/LoadDataFixturesDoctrineCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Loader.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/DataFixtures/ContainerAwareLoader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Loader/SymfonyFixturesLoader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/FixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/SharedFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/AbstractFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/ORMFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Fixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/DependentFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/AdminFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/AppFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/ApprenantFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/BriefFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/CmFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/CompetenceFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/CritereAdmissionFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/CritereEvaluationFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/EtatBriefFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/EtatBriefGroupeFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/FormateurFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/GroupeCompetenceFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/GroupeFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/GroupeTagFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/LangueFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/LivrableAtenduFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/NiveauFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/ProfileFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/PromoFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/ReferentielFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/RessourceFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/TagFixtures.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Purger/PurgerFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Purger/ORMPurgerFactory.php';

        $a = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($container);

        $b = ($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService'));

        $a->addFixtures([0 => ['fixture' => new \App\DataFixtures\AdminFixtures($b), 'groups' => []], 1 => ['fixture' => new \App\DataFixtures\AppFixtures($b), 'groups' => []], 2 => ['fixture' => new \App\DataFixtures\ApprenantFixtures($b), 'groups' => []], 3 => ['fixture' => new \App\DataFixtures\BriefFixtures(), 'groups' => []], 4 => ['fixture' => new \App\DataFixtures\CmFixtures($b), 'groups' => []], 5 => ['fixture' => new \App\DataFixtures\CompetenceFixtures(), 'groups' => []], 6 => ['fixture' => new \App\DataFixtures\CritereAdmissionFixtures(), 'groups' => []], 7 => ['fixture' => new \App\DataFixtures\CritereEvaluationFixtures(), 'groups' => []], 8 => ['fixture' => new \App\DataFixtures\EtatBriefFixtures(), 'groups' => []], 9 => ['fixture' => new \App\DataFixtures\EtatBriefGroupeFixtures(), 'groups' => []], 10 => ['fixture' => new \App\DataFixtures\FormateurFixtures($b), 'groups' => []], 11 => ['fixture' => new \App\DataFixtures\GroupeCompetenceFixtures(), 'groups' => []], 12 => ['fixture' => new \App\DataFixtures\GroupeFixtures(), 'groups' => []], 13 => ['fixture' => new \App\DataFixtures\GroupeTagFixtures(), 'groups' => []], 14 => ['fixture' => new \App\DataFixtures\LangueFixtures(), 'groups' => []], 15 => ['fixture' => new \App\DataFixtures\LivrableAtenduFixtures(), 'groups' => []], 16 => ['fixture' => new \App\DataFixtures\NiveauFixtures(), 'groups' => []], 17 => ['fixture' => new \App\DataFixtures\ProfileFixtures(), 'groups' => []], 18 => ['fixture' => new \App\DataFixtures\PromoFixtures(), 'groups' => []], 19 => ['fixture' => new \App\DataFixtures\ReferentielFixtures(), 'groups' => []], 20 => ['fixture' => new \App\DataFixtures\RessourceFixtures(), 'groups' => []], 21 => ['fixture' => new \App\DataFixtures\TagFixtures(), 'groups' => []]]);

        $container->privates['doctrine.fixtures_load_command'] = $instance = new \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand($a, ($container->services['doctrine'] ?? $container->getDoctrineService()), ['default' => new \Doctrine\Bundle\FixturesBundle\Purger\ORMPurgerFactory()]);

        $instance->setName('doctrine:fixtures:load');

        return $instance;
    }
}
