<?php

namespace ContainerWgrMl2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5Ll56vRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5Ll56vR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5Ll56vR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo_brief' => ['privates', 'App\\Repository\\BriefRepository', 'getBriefRepositoryService', true],
            'repo_etat' => ['privates', 'App\\Repository\\EtatBriefRepository', 'getEtatBriefRepositoryService', true],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
        ], [
            'repo_brief' => 'App\\Repository\\BriefRepository',
            'repo_etat' => 'App\\Repository\\EtatBriefRepository',
            'serializer' => '?',
        ]);
    }
}
