<?php

namespace ContainerWgrMl2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jfs2lN6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jfs2lN6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jfs2lN6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'apiService' => ['privates', 'App\\Services\\ApiService', 'getApiServiceService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo_Competence' => ['privates', 'App\\Repository\\CompetenceRepository', 'getCompetenceRepositoryService', true],
            'serialize' => ['services', 'serializer', 'getSerializerService', false],
        ], [
            'apiService' => 'App\\Services\\ApiService',
            'em' => '?',
            'repo_Competence' => 'App\\Repository\\CompetenceRepository',
            'serialize' => '?',
        ]);
    }
}
