<?php

namespace ContainerWgrMl2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G84dhgwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G84dhgw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G84dhgw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo_gr' => ['privates', 'App\\Repository\\GroupeRepository', 'getGroupeRepositoryService', true],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
        ], [
            'repo_gr' => 'App\\Repository\\GroupeRepository',
            'serializer' => '?',
        ]);
    }
}
