<?php

namespace Container7RmQOWM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LSXm0_VService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LSXm0.v' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LSXm0.v'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo_promo' => ['privates', '.errored.3kTNFn2', NULL, 'Cannot determine controller argument for "App\\Controller\\BriefController::getPromoIdBriefsId()": the $repo_promo argument is type-hinted with the non-existent class or interface: "App\\Controller\\Brie". Did you forget to add a use statement?'],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
        ], [
            'repo_promo' => '?',
            'serializer' => '?',
        ]);
    }
}
