<?php

namespace Container7RmQOWM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\ApiService' shared autowired service.
     *
     * @return \App\Services\ApiService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/ApiService.php';

        $a = ($container->privates['App\\Repository\\ProfileRepository'] ?? $container->load('getProfileRepositoryService'));

        return $container->privates['App\\Services\\ApiService'] = new \App\Services\ApiService(($container->privates['App\\Repository\\FormateurRepository'] ?? $container->load('getFormateurRepositoryService')), ($container->privates['App\\Repository\\CompetenceRepository'] ?? $container->load('getCompetenceRepositoryService')), $a, $a, ($container->services['serializer'] ?? $container->getSerializerService()), ($container->services['validator'] ?? $container->getValidatorService()), ($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService')));
    }
}
