<?php

namespace Container7RmQOWM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileSortiePersisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataPersisters\ProfileSortiePersister' shared autowired service.
     *
     * @return \App\DataPersisters\ProfileSortiePersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataPersister/DataPersisterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataPersister/ContextAwareDataPersisterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataPersisters/ProfileSortiePersister.php';

        return $container->privates['App\\DataPersisters\\ProfileSortiePersister'] = new \App\DataPersisters\ProfileSortiePersister(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
