<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7RmQOWM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7RmQOWM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7RmQOWM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7RmQOWM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7RmQOWM\App_KernelDevDebugContainer([
    'container.build_hash' => '7RmQOWM',
    'container.build_id' => 'eb8eef17',
    'container.build_time' => 1607017033,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7RmQOWM');
