<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMxnTj8H\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMxnTj8H/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMxnTj8H.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMxnTj8H\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMxnTj8H\App_KernelDevDebugContainer([
    'container.build_hash' => 'MxnTj8H',
    'container.build_id' => '4cd9f190',
    'container.build_time' => 1606938304,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMxnTj8H');
